### ISSUE TITLE
请问怎么使用呢？

### ISSUE THREAD

**Issue by sdutwsl** [AcceNoi/accenbot#11]

**Comment by wangzheooo** [comment]
同问

**Comment by AcceNoi** [comment]
@sdutwsl @wangzheooo  你好，很抱歉现在才回复。之前该项目（原dmzjbot）仅作为应用来编写，所以没有写quickstart，现在已经更名为accenbot框架且初步编写了quickstart，详细可见[Accenbot-Quickstart](https://github.com/AcceNoi/accenbot/blob/master/README-QUICKSTART.md)
